services:
  - type: web
    name: medibook-pro-backend
    env: node
    region: oregon
    plan: free
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://alilazim2005_db_user:Sxe5bSfVkEdd8pWd@cluster0.tc96wxl.mongodb.net/medibook?retryWrites=true&w=majority"
      - key: JWT_SECRET
        value: "ChangeThisSecret"
      - key: CLIENT_URL
        value: ""
  - type: static
    name: medibook-pro-frontend
    region: oregon
    plan: free
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://medibook-pro-backend.onrender.com/api"
